// src/js/pingpongHelper.js

const API_BASE_URL_GAME_PINGPONG = process.env.REACT_APP_API_BASE_URL_GAME_PINGPONG;
const WEBSOCKET_PINGPONG_URL = process.env.REACT_APP_WEBSOCKET_PINGPONG_URL;

export { API_BASE_URL_GAME_PINGPONG, WEBSOCKET_PINGPONG_URL };
