// src/js/trikiHelper.js

const API_BASE_URL_GAME_TRIKI = process.env.REACT_APP_API_BASE_URL_GAME_TRIKI;
const WEBSOCKET_TRIKI_URL = process.env.REACT_APP_WEBSOCKET_TRIKI_URL;

export { API_BASE_URL_GAME_TRIKI, WEBSOCKET_TRIKI_URL };
